config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  resources 'blog_posts', path: 'blog'
  post 'email_signup' => 'blog_posts#email_signup'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :title,:body,:author,:description
  # before_create :create_slug

  # def to_param
  #   slug
  # end
  #
  # def create_slug
  #   self.slug = self.title.parameterize
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :first_name, :last_name, :email, :password, :admin

  def admin?
    self.admin == true
  end

  def name
    self.first_name || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_admin?
  after_filter :store_location, unless: :devise_controller?
  # before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) << :username
    # devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email) }
  end

  def current_admin?
    current_user and current_user.admin == true
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || blog_posts_path
  end

  def after_sign_out_path_for(resource_or_scope)
    '/users/sign_in'
  end

  def store_location
    return unless request.get?
    if !request.xhr?
      session[:previous_url] = request.fullpath
    end
  end

  def user_root_path
    if current_user
      blog_posts_path
    else
      root_path
    end
  end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  # before_filter :authenticate, :except => [ :index, :show ]

  def index
    @blog_posts = BlogPost.all.order("created_at DESC")
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email_signup
    
  end

  private
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    def blog_post_params
      params[:blog_post]
    end

    def authenticate
      if current_user and current_user.admin == true
        authenticate_or_request_with_http_basic do |admin, password|
          name == "admin" && password == current_user.password
        end
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_filter :authenticate_user!, only: :index

  def index

  end
end

app/helpers/application_helper.rb
include FontAwesome::Rails::IconHelper
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "flash-messages container alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true)
    return markdown.render(text).html_safe
  end

end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog_posts/_cheatsheet.haml
.cheatsheet{style:'display:inline-block;border:1px solid gray;border-radius:6px;padding:20px'}
  %h1
    ="Simple Cheat Sheet (spaces are important)"
    %hr
  %h2
    ="Headings:"
    %br

  ="h1: #"
  %br
  ="h2: ##"
  %br
  ="h2: ###"
  %br
  ="h4: ####"
  %br
  ="h5: #####"
  %br
  ="h6: ######"
  %br
  %hr

  %h2
    ="Horizontal Rules (hr):"
    %br

  ="*** OR ___ OR ---"
  %br
  %hr

  %h2
    ="Bold:"
    %br

  ="**(your text)**"
  %br
  %hr

  %h2
    ="Italics"
    %br

  ="_(your text)_"
  %br
  %hr

  %h2
    ="Strikethrough:"
    %br

  ="~~(your text)~~"
  %br
  %hr

  %h2
    ="Bullets:"
    %br

  ="* (your text) OR - (your text) OR + (your text)"
  %br
  %hr

  %h2
    ="Numbered List:"
    %br

  ="(your number). (your text)"
  %br
  %hr

  %h2
    ="Code:"
    %br

  ="`(your code)`"
  %br
  %hr

  %h2
    ="Code block:"
    %br

  ="```(your code block)```"
  %br
  %hr

  %h2
    ="Image:"
    %br

  ="![your image title] (your image url)"
  %br
  %hr

  %h2
    ="Link:"
    %br

  ="[your link title](your link url)"
  %br

app/views/blog_posts/_form.html.haml
= form_for(@blog_post) do |f|
  - if @blog_post.errors.any?
    #error_explanation
      %h2
        = pluralize(@blog_post.errors.count, "error")
        prohibited this blog_post from being saved:
      %ul
        - @blog_post.errors.full_messages.each do |message|
          %li= message
  .form-group.col-md-6
    =f.label :title
    =f.text_field :title, class: "form-control"
    %br
    =f.label :description
    =f.text_area :description, class: "form-control"
    %br
    =f.label :body
    =f.text_area :body, cols: 10, rows: 20, class: "form-control"
    %br
    =f.submit class: "btn btn-primary"

app/views/blog_posts/_signup_form.haml
.email-signup-container
  %h2
    Sign up
  %hr{style:'background-color:#b7b7b7'}
  = form_for email_signup_path do |f|
    .form-group
      =f.label :email
      =f.email_field :email, class: "form-control"
      %br
      %br

      =f.submit "Subscribe to blog", class: 'btn subscribe-btn medium-text'

app/views/blog_posts/edit.html.haml
.gg-container.blog-page
  .blog-container{style:'background-color:white'}
    %h1 Editing Blog Post
    = link_to 'Show', @blog_post, class: 'btn btn-default'
    |
    = link_to 'Back to Index', blog_posts_path, class: 'btn btn-default'
    = render 'form'
    =render 'cheatsheet'

app/views/blog_posts/index.html.haml
.gg-container.blog-page
  .blog-container
    -if current_admin?
      = link_to '+ New Blog post', new_blog_post_path, class: 'btn btn-warning'
      %br
      %br
    -@blog_posts.each do |post|
      .post-container{style:"padding:20px;margin-bottom:20px;border-radius:6px;background-color:white"}
        %h4.grey-text=post.created_at.strftime("%B %e, %Y")
        %h1=post.title
        %h4.grey-text="by <strong>#{post.author}</strong>".html_safe
        %br
        =markdown(post.description)
        =link_to "Read more <span class='fa fa-chevron-right'></span>".html_safe, blog_post_path(post), class: 'btn btn-default'
        -if current_admin?
          %br
          %br
          = link_to 'Edit', edit_blog_post_path(post), class: 'btn btn-primary'
          = link_to 'Delete this post', blog_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  =render 'signup_form'

app/views/blog_posts/new.html.haml
.gg-container.blog-page
  .blog-container{style:'background-color:white'}
    %h1 New Blog Post
    = link_to 'Back to Index', blog_posts_path, class: 'btn btn-default'
    = render 'form'
    =render 'cheatsheet'

app/views/blog_posts/show.html.haml
.gg-container.blog-page
  .blog-container{style:'background-color:white'}
    -if current_admin?
      = link_to 'Edit', edit_blog_post_path(@blog_post), class: 'btn btn-primary'
      = link_to 'Delete this post', blog_post_path(@blog_post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
      = link_to 'Back to Index', blog_posts_path, class: 'btn btn-default'
    %h1{style:'line-height:1em'}=@blog_post.title if @blog_post.title
    %h4{style:'color:gray'}="by #{@blog_post.author}"
    %br
    =@blog_post.created_at.strftime("%B %e, %Y")
    %hr
    %p=markdown(@blog_post.body) if @blog_post.body
  =render 'signup_form'

app/views/home/index.haml
-# #home-hero
#home-container
  #home-hero-text.col-md-7.medium-text
    Craft Cocktails
    %br
    Made to Impress
    .hero-subhead.light-text
      Unique cocktail recipes made simply by you
  #home-signup-container.col-md-5
    #home-signup-header
      Get pleasantly infrequent email updates
    #home-signup-content
      = form_for email_signup_path do |f|
        =f.text_field :first_name, placeholder: 'First Name', class: 'home-name-field home-form-fields'
        =f.text_field :first_name, placeholder: 'Last Name', class: 'home-name-field home-form-fields'
        =f.email_field :email, placeholder: 'Email address', class: 'home-email-field home-form-fields'
        %hr
        =f.submit "Sign up to hear about our progress", class: 'btn home-signup-btn'

app/views/layouts/_footer.haml
#footer-container
	.container

app/views/layouts/_navbar.haml
#navbar-container
  .container
    #nav-logo-container
      -# -unless current_page?(root_path)
      =link_to image_tag("green_garnish_icon.svg",width:50), root_path
    #nav-links
      %ul.hidden-xs.hidden-sm
        -# %li= link_to "BLOG", blog_posts_path
        -# -if user_signed_in?
        -#   %li= link_to "#{current_user.name}", '#nav-mobile-menu'
        -#   %li= link_to "LOG OUT", destroy_user_session_path, method: :delete
        -# -else
        -#   %li= link_to "LOG IN", new_user_session_path
          -# %li= link_to "SIGN UP", new_user_registration_path, class: 'nav-sign-up'
      %ul#nav-mobile.visible-xs.visible-sm
        -# %li= link_to '<i class="fa fa-bars"></i>'.html_safe, '#nav-mobile-menu', id: 'nav-bars'
  .collapse#nav-mobile-menu
    .container.visible-xs.visible-sm
      .well#nav-mobile-menu-content
        %ul.nav.nav-pills.nav-stacked
          -# %li= link_to "BLOG", blog_posts_path
          -# -if user_signed_in?
          -#   %li= link_to "#{current_user.name}", '#nav-mobile-menu'
          -#   %li= link_to "LOG OUT", destroy_user_session_path, method: :delete
          -# -else
          -#   %li= link_to "LOG IN", new_user_session_path
            -# %li.active= link_to "SIGN UP", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Green Garnish
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    -unless current_page?(root_path)
      .navbar-spacing{style:'margin-top:70px'}
    =render partial: 'layouts/navbar'
    =flash_messages
    =yield
  -unless current_page?(root_path)
    =render 'layouts/footer'